; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.x"

; Profiles
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[drupaljapan][download][type] = ""
projects[drupaljapan][download][url] = ""
projects[drupaljapan][type] = "profile"

; Modules
projects[ctools][version] = "1.2"

projects[features_extra][version] = "1.x-dev"

projects[features][version] = "1.0"

projects[field_group][version] = "1.1"

projects[i18n][version] = "1.7"

projects[pathauto][version] = "1.2"

projects[strongarm][version] = "2.0"

projects[token][version] = "1.2"

projects[variable][version] = "2.1"

projects[views][version] = "3.5"

